---
deployment:
  tasks:
    - export MAINDEPLOYPATH=/home/zyankbqy/public_html
    - /bin/cp -Rf . $MAINDEPLOYPATH

    - export SUBDEPLOYPATH=/home/zyankbqy/rahman.padmatrader.com
    - /bin/cp -Rf . $SUBDEPLOYPATH
