---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zyankbqy/rahman.padmatrader.com
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .env $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
